const actionTypes = {
  EDIT_TICKER: 'EDIT_TICKER',
  REQUEST_SUMMARY: 'REQUEST_SUMMARY',
  RECEIVE_SUMMARY: 'RECEIVE_SUMMARY',
  EDIT_INTERVAL: 'EDIT_INTERVAL',
  REQUEST_TIMESERIES: 'REQUEST_TIMESERIES',
  RECEIVE_TIMESERIES: 'RECEIVE_TIMESERIES'
}

export default actionTypes
